[package]
name = "Wasmtime-embedding"
version = "0.1.0"
authors = ["Xendergo <not@my.email>"]
edition = "2018"

[lib]
crate_type = ["cdylib"]

[dependencies]
jni = "0.18.0"
wasmtime = "0.19.0"
wasmtime-wasi = "0.19.1"
wasi-common = "0.19.1"